In [1]:
import numpy as np

# Filtering Arrays

In [3]:
one_to_five = np.array([1,2,3,4,5])
one_to_five

array([1, 2, 3, 4, 5])

In [4]:
mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False])

# Fancy indexing
Indexing the array using the mask array

In [5]:
one_to_five[mask]

array([2, 4])

# ClassId and ClassSize

In [7]:
classroom_ids_and_sizes = np.array([[1,22],[2,21],[3,27],[4,26]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [8]:
# selecting those classes that having a even number of size
classroom_ids_and_sizes[:,1]

array([22, 21, 27, 26])

In [10]:
# if the class size is even then the resuling array will return true, if not false
classroom_ids_and_sizes[:,1] % 2 == 0

array([ True, False, False,  True])

## Now to get the exact class id, index the classroom_ids_and_sizes with the mask

In [16]:
filtered_ids = classroom_ids_and_sizes[classroom_ids_and_sizes[:, 1] % 2 == 0, 0]
filtered_ids

array([1, 4])