# Numpy import and using

In [1]:
import numpy as np

In [14]:
np.__version__

'2.1.1'

In [ ]:
my_list=[1,2,3,4,5]

In [27]:
my_list

[1, 2, 3, 4, 5]

In [28]:
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

## These are line magic command

In [12]:
!pip list

Package                   Version
------------------------- --------------
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.8.30
cffi                      1.17.1
charset-normalizer        3.3.2
comm                      0.2.2
debugpy                   1.8.5
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.1.0
fastjsonschema            2.20.0
fqdn                      1.5.1
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.2
idna                      3.10
ipykernel                 6.29.5
ipython                   8.27.0
isoduration               20.11.0
jedi                      0.19.1
Jinja2      

## This is command line command

In [13]:
%pwd

'/home/jovyan/work/Numpy_tutorials'

## Normal list arithmetics

In [4]:
list1 =[1,2,3,4,5,6]
list2=[1,2,3,4,5,6]
list3 = list1 + list2
list3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

## Numpy solves this problem with arithmetical operation directly with two arrays

In [6]:
np_array1 = np.array(list1)
np_array2 = np.array(list2)
np_array1 * np_array2

array([ 1,  4,  9, 16, 25, 36])

In [32]:
np_array3 = np_array1 + np_array2 ** 2
np_array3

array([ 2,  6, 12, 20, 30, 42])

In [33]:
type(np_array3)

numpy.ndarray

# Metrix
### Metrix are whose array, that are two dimensional

In [34]:
matrix_array = [[1,2,3],[4,5,6],[7,8,9]]
matrix_array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
np_matrix_array = np.array(matrix_array)
np_matrix_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np_matrix_array[1][1]

np.int64(5)

## 3D array

In [38]:
np_3d_list = np.array([[[1, 2, 3], 
                        [4, 5, 6], 
                        [7, 8, 9]],
                       
                       [[10, 11, 12], 
                        [13, 14, 15], 
                        [16, 17, 18]],
                       
                       [[19, 20, 21], 
                        [22, 23, 24], 
                        [25, 26, 27]]])

In [39]:
np_3d_list[1][1][-1]

np.int64(15)