In [2]:
import numpy as np

# Initializing Arrays, Zeros, Ones, Identity, Full, Rand, Randint, Randn

In [6]:
arr = np.array([2,3,4,5])
arr

array([2, 3, 4, 5])

In [15]:
print(arr.dtype)

int64


Provides the type of items

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

If the dtype or datatype is not provided, by defauld It will become flooting point

In [11]:
np.ones(5, dtype='int32')

array([1, 1, 1, 1, 1], dtype=int32)

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full((2,2),88)

array([[88, 88],
       [88, 88]])

Random array of 4 rows and 2 columns

In [3]:
np.random.rand(4,2)

array([[0.6606844 , 0.79083933],
       [0.00818883, 0.65226712],
       [0.83348121, 0.54369695],
       [0.1614313 , 0.04510128]])

Array of 10 items, value between 1-100

In [5]:
np.random.randint(1,100,10)

array([20, 28, 92, 80, 41, 82,  5, 51, 34, 12])

Size is providing the 3 rows and 3 column

In [6]:
np.random.randint(1,50,size=(3,3))

array([[14, 36, 14],
       [41, 36, 24],
       [20, 17,  8]])

In [7]:
np.random.randn(20)

array([-0.86953527, -1.42401776,  0.21008176, -1.14503133, -0.60272279,
       -0.09290297,  0.21320418,  0.91627859, -0.11145577, -0.93473927,
       -0.17264348, -0.94939037,  0.81235156, -1.30141166, -1.04865587,
        0.04136278, -0.73830685,  1.07717066,  0.2981499 , -0.70883335])

In [4]:
np.random.random((3,6))

array([[0.58979329, 0.99355723, 0.1107557 , 0.06217886, 0.20662383,
        0.44590705],
       [0.64032525, 0.05299123, 0.8944504 , 0.85013847, 0.8643972 ,
        0.68102975],
       [0.12777026, 0.76480381, 0.17988816, 0.17994506, 0.45614908,
        0.45602168]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])