# Indexing and slicing (2d array)

In [9]:
import numpy as np
array_2d = np.arange(24)
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
array_2d.reshape(8,3)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
array_2d[2]

array([ 8,  9, 10, 11])

In [22]:
array_2d[3,3]

np.int64(15)

In [22]:
array_2d[3][3]

np.int64(15)

In [19]:
array_2d[3][1:3]

array([13, 14])

In [20]:
array_2d[[1,2,3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [23]:
array_2d[:,[2]]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [24]:
array_2d[:][2]

array([ 8,  9, 10, 11])