In [1]:
import numpy as np

# "Shape" describes the shape on an array.

In [6]:
np_array = np.zeros((2,3), dtype='int32')
np_array.shape

(2, 3)

# "Flatten" helps to convert the multi dimensional array into single dimensional one

In [8]:
num_array = np.array([[1,2],[3,4],[5,6],[7,8]])
num_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
num_array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# "Reshape" can reshape the 1d array into 2d array

In [13]:
num_array.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])