# Indexing and slicing (2d array)
### Slicing produces new array of sliced data

## "arange" function helps to make numeric ascending array

In [7]:
import numpy as np
array_2d = np.arange(24)
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## "shape" can make 2d array, however shape is an attribute

In [15]:
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## "reshape" is similar like shape but reshape is function not and attribute

In [17]:
array_2d.reshape(8,3)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Selecting or slicing array row wise

In [18]:
array_2d[2]

array([ 8,  9, 10, 11])

## Slicing both row and column wise to get a specific data

In [22]:
array_2d[3,3]

np.int64(15)

## Slicing data column wise

In [23]:
array_2d[:,[2]]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

## Slicing data range row wise

In [19]:
array_2d[3][1:3]

array([13, 14])

## Slicing Multiple rows

In [20]:
array_2d[[1,2,3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Making a subset of 2d array

In [21]:
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [24]:
array_2d[:][2]

array([ 8,  9, 10, 11])

In [20]:
big_array = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
                       [10, 11, 12, 13, 14, 15, 16, 17, 18],
                       [19, 20, 21, 22, 23, 24, 25, 26, 27],
                       [28, 29, 30, 31, 32, 33, 34, 35, 36],
                       [37, 38, 39, 40, 41, 42, 43, 44, 45],
                       [46, 47, 48, 49, 50, 51, 52, 53, 54],
                       [55, 56, 57, 58, 59, 60, 61, 62, 63],
                       [64, 65, 66, 67, 68, 69, 70, 71, 72],
                       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

## Slicing as 2d array

In [22]:
new = big_array[2:5, 2:5]
new

array([[21, 22, 23],
       [30, 31, 32],
       [39, 40, 41]])

## Slicing as 2d array with steps

In [25]:
big_array[2:7:2, 2:7:2]

array([[21, 23, 25],
       [39, 41, 43],
       [57, 59, 61]])

## Sort function

In [26]:
unsorted = np.array([[31, 82, 68, 36, 95, 17, 93, 30, 95],
                     [92, 64, 31,  9, 51, 67,  2, 51, 83],
                     [19, 41, 11, 33, 15, 96, 25, 68, 67],
                     [ 3, 36, 94, 98, 72, 74, 32, 49, 94],
                     [71, 55, 51, 85, 25, 85,  8, 31, 51],
                     [26, 91, 70, 93, 22, 78, 87, 86, 52],
                     [23, 80, 41, 34,  3, 64, 55, 86, 69],
                     [49, 67, 23, 91, 62, 97, 24, 12, 44],
                     [44, 91, 86, 82, 42, 36, 96, 91,  8]])

## row wise sorting or axis = 1

In [27]:
np.sort(unsorted)

array([[17, 30, 31, 36, 68, 82, 93, 95, 95],
       [ 2,  9, 31, 51, 51, 64, 67, 83, 92],
       [11, 15, 19, 25, 33, 41, 67, 68, 96],
       [ 3, 32, 36, 49, 72, 74, 94, 94, 98],
       [ 8, 25, 31, 51, 51, 55, 71, 85, 85],
       [22, 26, 52, 70, 78, 86, 87, 91, 93],
       [ 3, 23, 34, 41, 55, 64, 69, 80, 86],
       [12, 23, 24, 44, 49, 62, 67, 91, 97],
       [ 8, 36, 42, 44, 82, 86, 91, 91, 96]])

## column wise sorting

In [28]:
np.sort(unsorted, axis=0)

array([[ 3, 36, 11,  9,  3, 17,  2, 12,  8],
       [19, 41, 23, 33, 15, 36,  8, 30, 44],
       [23, 55, 31, 34, 22, 64, 24, 31, 51],
       [26, 64, 41, 36, 25, 67, 25, 49, 52],
       [31, 67, 51, 82, 42, 74, 32, 51, 67],
       [44, 80, 68, 85, 51, 78, 55, 68, 69],
       [49, 82, 70, 91, 62, 85, 87, 86, 83],
       [71, 91, 86, 93, 72, 96, 93, 86, 94],
       [92, 91, 94, 98, 95, 97, 96, 91, 95]])